version: '3.9'

services:
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  web:
    build: .
    command: gunicorn myproject.wsgi:application --bind 0.0.0.0:8000
    working_dir: /app/app
    volumes:
      - .:/app
      - static_volume:/app/app/static  # Share with nginx
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: django-nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/static  # Mount static files
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
