pipeline {
    agent any
    stages {
        stage('Setting up Python Virtual Env')
        {
        steps {
            sh '''
            chmod +x django_projects/talat_parwez/envsetup.sh
            django_projects/talat_parwez/envsetup.sh
            '''
            }
        }
        stage('Setting up Gunicorn')
        {
            steps {
                sh '''
                chmod +x django_projects/talat_parwez/gunicorn.sh
                django_projects/talat_parwez/gunicorn.sh
                '''
            }
        }
        stage('Setting up Nginx') {
            steps {
                sh '''
                chmod +x django_projects/talat_parwez/nginx.sh
                django_projects/talat_parwez/nginx.sh
                ''' 
            }
        }
    }
}