pipeline {
    agent any

    environment {
        PROJECT_NAME = 'django-fullstack'
        IMAGE_NAME = 'us-central1-docker.pkg.dev/tp-deployment-project/django-fullstack/django-fullstack'
        GCP_VM_IP = '35.224.94.179'
        SSH_USER = 'root'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'master', url: 'https://github.com/stalat/Projects.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('django_projects/django-fullstack') {
                    sh """
                        docker build -t ${IMAGE_NAME} .
                    """
                }
            }
        }

        stage('Push to Artifact Registry') {
            steps {
                withCredentials([file(credentialsId: 'gcp-key', variable: 'GCLOUD_KEY')]) {
                    sh '''
                        gcloud auth activate-service-account --key-file=$GCLOUD_KEY
                        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
                        docker push ${IMAGE_NAME}
                    '''
                }
            }
        }

        stage('Deploy on GCP VM') {
            steps {
                sshagent(credentials: ['gcp-ssh-key']) {
                    sh """
                        ssh -o StrictHostKeyChecking=no ${SSH_USER}@${GCP_VM_IP} '
                            if [ ! -d /root/django-fullstack ]; then
                                echo "📦 Cloning repo first time..."
                                git clone https://github.com/stalat/Projects.git /root/django-fullstack
                            fi

                            cd /root/django-fullstack/django_projects/django-fullstack

                            echo "🔄 Pulling latest code..."
                            git pull

                            echo "🧹 Shutting down existing containers..."
                            docker-compose down

                            echo "🚀 Building and starting containers..."
                            docker-compose up -d --build
                        '
                    """
                }
            }
        }
    }

    post {
        success {
            echo '✅ Deployment completed successfully!'
        }
        failure {
            echo '❌ Deployment failed!'
        }
    }
}
