# Generated by Django 4.2.3 on 2023-07-26 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image_01",
                    models.ImageField(blank=True, upload_to="portfolio_image"),
                ),
                (
                    "image_02",
                    models.ImageField(blank=True, upload_to="portfolio_image"),
                ),
                (
                    "image_03",
                    models.ImageField(blank=True, upload_to="portfolio_image"),
                ),
                (
                    "image_04",
                    models.ImageField(blank=True, upload_to="portfolio_image"),
                ),
                (
                    "image_05",
                    models.ImageField(blank=True, upload_to="portfolio_image"),
                ),
                (
                    "image_06",
                    models.ImageField(blank=True, upload_to="portfolio_image"),
                ),
                (
                    "image_07",
                    models.ImageField(blank=True, upload_to="portfolio_image"),
                ),
                (
                    "image_08",
                    models.ImageField(blank=True, upload_to="portfolio_image"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(default="")),
                ("company", models.CharField(max_length=100)),
                ("city", models.CharField(default="", max_length=100)),
                ("website", models.URLField(default="")),
                ("phone", models.IntegerField(default=0)),
                ("image", models.ImageField(blank=True, upload_to="profile_image")),
                ("resume", models.FileField(upload_to="resume_folder")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("company_description", models.TextField(default="")),
                ("designation", models.CharField(max_length=200)),
                ("profile", models.TextField(default="")),
                ("from_date", models.CharField(blank=True, max_length=100)),
                ("to_date", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sin_app.userprofile",
                    ),
                ),
            ],
        ),
    ]
