# Generated by Django 5.0 on 2023-12-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomerDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email_account", models.EmailField(max_length=254)),
                ("message", models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
